all:
  hosts:
    master01:
      ansible_host: 10.25.0.122
    worker01:
      ansible_host: 10.25.0.111
    worker02:
      ansible_host: 10.25.0.63
  children:
    kube_control_plane:
      hosts:
        master01:
    kube_node:
      hosts:
        master01:
        worker01:
        worker02:
    etcd:
      hosts:
        master01:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}