[all]
master01 ansible_host=10.25.0.170 ip=10.25.0.170 etcd_member_name=master01
master02 ansible_host=10.25.1.250 ip=10.25.1.250 etcd_member_name=master02
master03 ansible_host=10.25.2.16 ip=10.25.2.16 etcd_member_name=master03
worker01 ansible_host=10.25.0.143 ip=10.25.0.143
worker02 ansible_host=10.25.1.32 ip=10.25.1.32
worker03 ansible_host=10.25.2.104 ip=10.25.2.104

[bastion]
cicd ansible_host=43.199.203.119 ansible_user=ubuntu

[kube_control_plane]
master01
master02
master03

[etcd]
master01
master02
master03

[kube_node]
master01
master02
master03
worker01
worker02
worker03

[calico_rr]

[k8s_cluster:children]
kube_control_plane
kube_node
calico_rr