all:
  children:
    loadbalancer:
      hosts:
        loadbalancer:
          ansible_host: 10.25.10.253
          hostname: loadbalancer
    servers:
      hosts:
        cicd:
          ansible_host: 10.25.0.232
          hostname: cicd
        gitlab:
          ansible_host: 10.25.0.131
          hostname: gitlab
        rancher:
          ansible_host: 10.25.0.184
          hostname: rancher
    masters:
      hosts:
        master01:
          ansible_host: 10.25.0.122
          hostname: master01
    workers:
      hosts:
        worker01:
          ansible_host: 10.25.0.111
          hostname: worker01
        worker02:
          ansible_host: 10.25.0.63
          hostname: worker02
