---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        timeout: 300

    - name: Add hosts entries
      blockinfile:
        path: /etc/hosts
        block: "{{ hosts_entries | b64decode }}"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

    - name: Set password for ubuntu user
      user:
        name: ubuntu
        password: "{{ 'Ubuntu' | password_hash('sha512') }}"

    - name: Set timezone
      timezone:
        name: Asia/Ho_Chi_Minh

    - name: Set hostname
      hostname:
        name: "{{ hostname }}"